# Generated by Django 3.1.5 on 2021-01-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('bedroomNo', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sellerName', models.CharField(max_length=255)),
                ('sellNo', models.BigIntegerField()),
                ('solicitorName', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
