# Generated by Django 3.1.5 on 2021-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210201_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='buyer_number',
            field=models.CharField(max_length=15),
        ),
    ]
