# Generated by Django 3.1.5 on 2021-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210201_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
