# Generated by Django 3.1.5 on 2021-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210209_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.IntegerField(),
        ),
    ]
