"""
Django settings for register_sys project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lcioabe=3z30xjvfg4%@xc2k=8f(eh2=!h+xs$)iaq*uiwiarn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# OVER HERE I CAN ADD THE DOMIAN NAMES WHERE I WANT THIS SITE TO BE HOSTED AT. ON DEFAULT ITS MY LOCALHOST.
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',  # INSIDE THIS ACCOUNTS FOLDER, IS WHERE ALL THE PYTHON FILES ARE WRITTEN
    # THIS HOUSES FOLDER CONTAINS ALL THE RELEVANT FILES THAT WILL DISPLAY ALL THE HOUSES DETAILS.
    'houses',
    # THIS HOUSELIST FOLDER WILL INCLUDE ALL THE FILES WHICH WILL SAVE ALL THE DETAILS OF THE HOUSES THAT ARE SOLD.
    'houselist',
    # THIS MODULE WAS INSTALLED USING PIP MODULE. THIS ALLOWS ME TO CREATE AND LAYOUT MY REGISTER/LOGIN FORMS NICELY.
    'crispy_forms',

]

# Bootstrap is a library, that is used to make the user interface more better.
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# These files are default files installed by Django
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'housebuyers.urls'

#  This template settings includes all my HTML file
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # THIS IS WHERE I LINKED ALL MY HTML FILES, THAT THE WEB SEES.
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'housebuyers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#  THIS IS WHERE I LINKED MY DATABASE TO POSTGRES SQL USING DJANGO
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'houses',
        'USER': 'postgres',
        'PASSWORD': 'pruthvi123',
        'HOST': 'localhost'  # running on my local pc
    }
}

# THE REST ARE SOME DEFAULT SETTINGS GIVEN BY DJANGO WHICH DOESN'T MATTER TOO MUCH.

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
